### ISSUE TITLE
Review of the activator tutorial

### ISSUE THREAD

**Issue by ShokuninSan** [openforce/spark-mllib-scala-play#19]
It would assist us greatly to get feedback on the tutorials from people who were not involved with them.

**Comment by oF-MM** [comment]
* + Install worked with small confusion due to long download time and no response on console.
* + Startup via activator ui worked fine.
* + Tests worked fine.
* ~ Tutorial. Please adapt the intro according to our face to face talk.
* - If you find the time, remove s from log.debug(s"text") statements. :)
